# http://eslint.org/docs/rules/

parserOptions:
  sourceType: module
env:
  browser: true
  commonjs: true
  jquery: true
  node: false
plugins:
  - simple-import-sort
rules:
  # Import
  simple-import-sort/sort: 1
  import/order: 0
