# https://eslint.org/docs/rules/

root: true
parserOptions:
  sourceType: script
  ecmaVersion: 2020
env:
  es6: true
  node: true
plugins:
  - prettier
  - import
settings:
  import/resolver:
    node: {}
    webpack:
      config:
        resolve:
          modules:
            - templates/client
            - scss
            - node_modules
          alias:
            jquery: 'jquery/dist/jquery.slim'
            nunjucks: 'nunjucks/browser/nunjucks-slim'
        resolveLoader:
          alias:
            sassjson: 'sass-json-loader'
  import/external-module-folders:
    - 'node_modules'
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:prettier/recommended
rules:
  # Prettier
  prettier/prettier:
    - 2
    - singleQuote: true

  # Import
  import/order:
    - 1
    - newlines-between: always
      alphabetize:
        order: 'asc'
  import/named: 1

  # Possible Errors
  getter-return: 2
  no-await-in-loop: 2
  no-template-curly-in-string: 2

  # Best Practices
  array-callback-return: 2
  block-scoped-var: 2
  class-methods-use-this: 1
  consistent-return: 2
  curly: 2
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-console: 1
  no-div-regex: 2
  no-else-return: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-str: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 2
  no-proto: 2
  no-return-assign: 2
  no-return-await: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-return: 2
  no-void: 2
  no-warning-comments:
    - 1
    - terms:
        - todo
        - fixme
        - '@@@'
  no-with: 2
  prefer-promise-reject-errors:
    - 2
    - allowEmptyReject: true
  radix: 2
  require-await: 2
  yoda:
    - 2
    - never
    - exceptRange: true

  # Strict Mode
  strict: 2

  # Variables
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-undef-init: 2
  no-use-before-define: 2

  # Node.js and CommonJS
  global-require: 2
  handle-callback-err: 2
  no-buffer-constructor: 2
  no-mixed-requires: 2
  no-new-require: 2
  no-path-concat: 2
  no-process-env: 2
  no-process-exit: 2
  no-sync: 2

  # Stylistic Issues
  func-name-matching: 2
  func-names:
    - 2
    - as-needed
  func-style: 2
  linebreak-style: 2
  lines-between-class-members: 2
  max-len:
    - 2
    - ignoreComments: true
      ignoreStrings: true
      ignorePattern: '^import .*'
  new-cap:
    - 2
    - capIsNewExceptions:
        - Deferred
        - Event
  no-array-constructor: 2
  no-bitwise: 2
  no-continue: 2
  no-lonely-if: 2
  no-negated-condition: 2
  no-nested-ternary: 2
  no-new-object: 2
  no-plusplus: 2
  no-tabs: 2
  no-unneeded-ternary: 2
  one-var:
    - 2
    - uninitialized: always
      initialized: never
  operator-assignment:
    - 2
    - never
  spaced-comment: 2

  # ECMAScript 6
  arrow-body-style: 2
  no-duplicate-imports: 0
  no-useless-computed-key: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-var: 2
  object-shorthand: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-destructuring:
    - 2
    - array: false
  prefer-numeric-literals: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  sort-imports: 0
  symbol-description: 2
