# See https://github.com/sasstools/sass-lint/tree/develop/docs/rules
# ------------------------------------------------------------------

# Rules
rules:
  # Extends
  extends-before-declarations: 2
  extends-before-mixins: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 1
    - exclude:
      - before
      - after
      - above
      - below
      - between
      - wrap-content

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 0

  # nesting
  force-attribute-nesting: 2
  force-element-nesting: 1
  force-pseudo-nesting: 2

  # Style Guide
  border-zero: 2
  brace-style: 2
  clean-import-paths:
    - 1
    - leading-underscore: false
      filename-extension: false
  empty-args: 2
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  indentation: 1
  leading-zero:
    - 2
    - include: true
  mixin-name-format: 2
  nesting-depth:
    - 2
    - max-depth: 3
  placeholder-name-format: 2
  property-sort-order: 2
  quotes: 2
  shorthand-values: 1
  url-quotes: 2
  variable-for-property: 0
  variable-name-format: 2
  zero-unit: 2

  # Inner Spacing
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2

  # Final Items
  final-newline: 2
  trailing-semicolon: 2
