packageExtensions:
  markdown-it-anchor@*:
    peerDependenciesMeta:
      "@types/markdown-it":
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
